version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Hadolint
          command: docker pull hadolint/hadolint
      - run:
          name: Lint Dockerfile
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile
  
  test-app:
    docker:
      - image: cimg/go:1.15
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: 'sh build_push_image_karsajobs.sh'

workflows:
  karsajobs-backend-workflow:
    jobs:
      - lint-dockerfile

      - test-app:
          requires:
            - lint-dockerfile

      - build-app-karsajobs:
          requires:
            - test-app